### ISSUE TITLE
Непонятки

### ISSUE THREAD

**Issue by Tirixk** [devapromix/lotgd#22]
Привет, Я скачал Ваш исходник, А что дальше? Я нигде не нашел подключение к базе данных, на Вашем официальном сайте нельзя создать аккаунт.

**Comment by devapromix** [comment]
Привет! Скачайте сначала форумный движок https://fluxbb.org/, установите. Затем с заменой файлов скопируйте исходный код игры. Дамп БД скоро закоммичу.

**Comment by devapromix** [comment]
Регистрация не отключена, проверил. С какой ошибкой Вы столкнулись при регистрации?

**Comment by devapromix** [comment]
Ошибки устранены. Попробуйте зарегистрироваться снова.

**Comment by Tirixk** [comment]
доброе утро, Сейчас попробую зарегистрироваться,  тогда уже обновлённую версию  выложите пожалуйста с исправленной регистрацией.

**Comment by Tirixk** [comment]
Удалось зарегистрироваться, хотел спросить что  это за текст он везде присутствует
Главная площадь города
-----------
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

===========
Ещё, там где расписаны статы, можете к их изображениям  с помощью атрибута Alt прописать что это за стад, желательно на русском языке
 Я незрячий, пользуюсь озвучкой, и непонятно какие цифры чему принадлежат.
Простите если чем обидел.

**Comment by devapromix** [comment]
Привет! Вы меня ничем не обидели. Все норм. Спасибо за интерес к игре. Но пока игра на очень ранней стадии разработки. Локаций и действий мало и поиграть врядли получится. Про Lorem ipsum: пока тексты описания не готовы, вместо них используется этот текст-заполнитель, почитайте больше тут - https://ru.wikipedia.org/wiki/Lorem_ipsum. Про атрибут alt - сделаю, на русском языке, так как игра и планируется на русском языке.
